name: Release image
on:
  push:
    tags:
    - v*
  workflow_dispatch:
jobs:
  build:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - run: make docker-build
    - name: Tag and push
      run: |
        GIT_VERSION=$(git describe --tags --dirty --always)
        REGISTRY=ghcr.io/${{ github.repository_owner }}
        IMG_NAME=pod-graceful-drain

        tag-and-push() { docker tag $1 $2 && docker push $2; }

        tag-and-push $IMG_NAME:latest $REGISTRY/$IMG_NAME:$GIT_VERSION

        LATEST_TAG="$(git describe --tags --dirty --always --abbrev=0)"
        if git diff --quiet "$LATEST_TAG"; then
          tag-and-push $IMG_NAME:latest $REGISTRY/$IMG_NAME:latest
        fi