name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Install helm kubeval
        run: helm plugin install https://github.com/instrumenta/helm-kubeval
      - run: make test manifests docker-build
      - name: Manifests are up to date
        run: git diff --exit-code -- config/
      - run: helm lint charts/pod-graceful-drain --strict
      - run: helm kubeval charts/pod-graceful-drain
      - uses: codecov/codecov-action@v1
        with:
          file: ./cover.out